import { Zilla_Slab } from "next/font/google";
import "./globals.css";

const zilla_slab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head><meta name="viewport" content="width=device-width, initial-scale=1.0"></meta></head>
      <body className={zilla_slab.className}>{children}</body>
    </html>
  );
}
